language: go
go:
- 1.4
- tip
env:
  global:
  - GH_REF=github.com/NeowayLabs/dchan.git
  - PLAN9=/tmp/plan9
  - PATH=$PATH:$PLAN9/bin
install:
  - cd $HOME/gopath/src/github.com/NeowayLabs/dchan && make build
script:
  - make
  - bash ./scripts/deploy-docs.sh
before_install:
  - sudo rm /etc/dpkg/dpkg.cfg.d/multiarch
  - curl https://repogen.simplylinux.ch/txt/sources_52e6d80fad9c7b2d617f3c30b5fef19e6b154d32.txt| sudo tee /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y emacs24
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" texlive-full
  - sudo apt-get install -y ditaa
  - sudo cp /usr/share/ditaa/ditaa.jar /usr/bin/ditaa.jar
  - sudo pip install codecov
  - cd /tmp && git clone https://github.com/fniessen/orgmk
  - cd /tmp/orgmk && ORGMK_EL=$HOME/gopath/src/github.com/NeowayLabs/dchan/scripts/orgmk.el make -e && sudo make install
  - cd /tmp && git clone https://github.com/tiago4orion/plan9port.git plan9
  - cd /tmp/plan9 && ./INSTALL
  - sudo addgroup travis fuse
  - sudo chmod 755 /etc/fuse.conf
  - go get -v github.com/wadey/gocovmerge
notifications:
  email:
    - tiago.natel@neoway.com.br
