language: go
go:
- 1.4
- tip
env:
  global:
    - secure: "TA4S7GidJjp/p8M/ecRCdeVwbqakd3U/v5t4TN/c1E56yhqwR4659EVlMhaDlsZQLaJ6fUGU/g5kKl5BRBNpFwNyUmxv3KldnpQzj6nblfRhhNlqx1Yh8CCRpwrjOJwsjZ0OmbgXrMcA3JICHPWA2GFDuAyBRU2hdtIyPP2zWo7Lq8PG67vsYA/fOKzRKtBXyz5ui2ti0eZV+nRjhv4M7jSHmmZr/oMzdmMyXuFMMyaWMPbD0pXzUh/zq5Rzv6F/NZZaLtem+1AMV3actnuyxuwM266QvSw9ZQk4iA7dE5zx5JNwCz6eIeZ/ZX29mP3Z2AkIXLVrLPx022gH/HdB18BIviUb2FE/xSdeeswuLiZQpdeh1meER1rHVeHArw+gBDvEhkaYXSqcBIttqTmJeJZHFGl/ONLU7BYbD54HLEfL/IVeLJQBKH/ML66aiofg5eof659ShYZ3VT5M96mjFnufSTJIPg8tKrBG9AnYCCEHSA2vJlS3Hn6cLzv5RdBZBgIetrsdpoK7/g8a1ysOWDU84JxQBhxMisOpmKr53nsufXAeq4T1b6F6OI2cF2mZ5I80aab9w74XEbouHmE5c92bBDhgWTOFgkc2RswoJ4ZKUk5UGCHJmzTMZ4XZ7NeTrylRP7HlL1W1+OmiP4ngtmO96nTsyWlRlz1V+9mBU/g="
    - GH_REF=github.com/NeowayLabs/dchan.git
    - PLAN9=/tmp/plan9
    - PATH=$PATH:$PLAN9/bin
install:
  - cd $HOME/gopath/src/github.com/NeowayLabs/dchan && make build
script:
  - make test
  - bash ./scripts/deploy-docs.sh
before_install:
  - sudo rm /etc/dpkg/dpkg.cfg.d/multiarch
  - curl https://repogen.simplylinux.ch/txt/sources_52e6d80fad9c7b2d617f3c30b5fef19e6b154d32.txt| sudo tee /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y emacs24
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" texlive-full
  - sudo apt-get install -y ditaa
  - sudo mkdir -p /usr/share/emacs/24.4/lisp/contrib/scripts/ && sudo cp /usr/share/ditaa/ditaa.jar /usr/share/emacs/24.4/lisp/contrib/scripts/ditaa.jar
  - sudo pip install codecov
  - cd /tmp && git clone https://github.com/fniessen/orgmk
  - cd /tmp/orgmk && ORGMK_EL=$HOME/gopath/src/github.com/NeowayLabs/dchan/scripts/orgmk.el make -e && sudo make install
  - cd /tmp && git clone https://github.com/tiago4orion/plan9port.git plan9
  - cd /tmp/plan9 && ./INSTALL
  - sudo addgroup travis fuse
  - sudo chmod 755 /etc/fuse.conf
notifications:
  email:
    - tiago.natel@neoway.com.br
