language: go

go:
  - 1.4
  - tip
install:
  - cd $HOME/gopath/src/github.com/NeowayLabs/dchan
  - make tangle
  - go get -d -v ./unix/dchan/...
  - make build
script:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get -u github.com/golang/lint/golint
  - go get github.com/nielsdraaisma/godep
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - cd unix/dchan && go test -v ./...
#  - goveralls -coverprofile=coverage.txt -service=travis-ci
before_install:
  - sudo add-apt-repository ppa:ubuntu-elisp/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install --force-yes emacs-snapshot
  - sudo pip install codecov
  - cd /tmp && git clone https://github.com/fniessen/orgmk
  - cd /tmp/orgmk && make && sudo make install
after_success:
  codecov
notifications:
  email:
    - tiago.natel@neoway.com.br
