language: go
go:
- 1.4
- tip
env:
  global:
    - GH_REF: github.com/NeowayLabs/dchan.git
    - PLAN9=/tmp/plan9
    - PATH=$PATH:$PLAN9/bin
    - secure: iPTnXnTdItHfKTuhuSTYWV/mbM8tEGulRuOxaDym5ffGkygNPkfdGFAJX1WeCJr66b4KsYBj6y19eqixXuW8TiLoDOu9/e+sNMIyqX4rJgtpz2vXwGpOE4SRz2WmJSBtnzyZIGYJKSTk2dzxbvd9tgJdBjjC0P3fhuJogFSdjHunqsGWNleNH90K0mTY8/NgpTcCG8deVt/HS4kS1KpdCkEwDxzMSTGJyz637uBmVwRMxRlgtunwlFR0NhwmwQdRTOx3YTfL91+aeLOJrvyspiPIaqYcSy3UhGiw44fiET4XjikWjpTBBQUNcbpuKVCoEAdIykLI95oebaw7suHWX7P8mTu0kSO6QYuYDCHLxwfLfBtrUM9uazvo6bas1sVJDSMI9bvYEW6DZqnTQbbxFi+ONKBMwv27lzDfLPIZFwbOmg0jFaXm3jteHYszHVXIemGDUPK4rTnjVwhVKYfyDB5smU/U+AnsQlFmF97UZTTjwHmDPWeQ2IPrqdBZ8Vw70iheqiQtjOhftkH7uaVbVoe1B5k1KdiyKGUjfFCYkFhqPewnzq3qS78BW2XkMhGZsZoP4eIkx97ydck7h+vqtSaVX8ER+kaNDnRsy63mLYUzVtCAszke/KAarUO7k/MyBe+tGDOwFROnhOX9thW6MF3ewn3QxF7Rfk66xPGiOYE=
install:
  - cd $HOME/gopath/src/github.com/NeowayLabs/dchan && make build
script:
  - make test
  - ./scripts/deploy-docs.sh
before_install:
  - sudo rm /etc/dpkg/dpkg.cfg.d/multiarch
  - curl https://repogen.simplylinux.ch/txt/sources_52e6d80fad9c7b2d617f3c30b5fef19e6b154d32.txt| sudo tee /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y emacs24
  - sudo apt-get install -y texlive-latex-recommended
  - sudo apt-get install -y ditaa
  - find /usr | grep ditaa
  - sudo mkdir -p usr/share/emacs/24.4/lisp/contrib/scripts/ && sudo cp /usr/share/java/ditaa/ditaa-0_9.jar usr/share/emacs/24.4/lisp/contrib/scripts/ditaa.jar
  - sudo pip install codecov
  - cd /tmp && git clone https://github.com/fniessen/orgmk
  - cd /tmp/orgmk && ORGMK_EL=$HOME/gopath/src/github.com/NeowayLabs/dchan/scripts/orgmk.el make -e && sudo make install
  - cd /tmp && git clone https://github.com/tiago4orion/plan9port.git plan9
  - cd /tmp/plan9 && ./INSTALL
  - sudo addgroup travis fuse
  - sudo chmod 755 /etc/fuse.conf
notifications:
  email:
    - tiago.natel@neoway.com.br
